//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace News2025.TomcatSystem {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="INEWSSystemPortBinding", Namespace="http://avid.com/inewssystem")]
    public partial class INEWSSystem : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConnectOperationCompleted;
        
        private System.Threading.SendOrPostCallback DisconnectOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsConnectedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFolderChildrenOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback HasNewMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetQueuesFormOperationCompleted;
        
        private System.Threading.SendOrPostCallback WatchQueueForChangesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChangedQueuesOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveWatchForQueueChangesOperationCompleted;
        
        private System.Threading.SendOrPostCallback PerformSimpleSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveSearchResultsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterNotificationServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelSearchOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public INEWSSystem() {
            this.Url = global::News2025.Properties.Settings.Default.News2025_TomcatSystem_INEWSSystem;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConnectCompletedEventHandler ConnectCompleted;
        
        /// <remarks/>
        public event DisconnectCompletedEventHandler DisconnectCompleted;
        
        /// <remarks/>
        public event IsConnectedCompletedEventHandler IsConnectedCompleted;
        
        /// <remarks/>
        public event GetFolderChildrenCompletedEventHandler GetFolderChildrenCompleted;
        
        /// <remarks/>
        public event GetMessageCompletedEventHandler GetMessageCompleted;
        
        /// <remarks/>
        public event HasNewMessageCompletedEventHandler HasNewMessageCompleted;
        
        /// <remarks/>
        public event SendMessageCompletedEventHandler SendMessageCompleted;
        
        /// <remarks/>
        public event GetQueuesFormCompletedEventHandler GetQueuesFormCompleted;
        
        /// <remarks/>
        public event WatchQueueForChangesCompletedEventHandler WatchQueueForChangesCompleted;
        
        /// <remarks/>
        public event GetChangedQueuesCompletedEventHandler GetChangedQueuesCompleted;
        
        /// <remarks/>
        public event RemoveWatchForQueueChangesCompletedEventHandler RemoveWatchForQueueChangesCompleted;
        
        /// <remarks/>
        public event PerformSimpleSearchCompletedEventHandler PerformSimpleSearchCompleted;
        
        /// <remarks/>
        public event RetrieveSearchResultsCompletedEventHandler RetrieveSearchResultsCompleted;
        
        /// <remarks/>
        public event RegisterNotificationServiceCompletedEventHandler RegisterNotificationServiceCompleted;
        
        /// <remarks/>
        public event CancelSearchCompletedEventHandler CancelSearchCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ConnectResponse", Namespace="http://avid.com/inewssystem/types")]
        public ConnectResponseType Connect([System.Xml.Serialization.XmlElementAttribute("Connect", Namespace="http://avid.com/inewssystem/types")] ConnectType Connect1) {
            object[] results = this.Invoke("Connect", new object[] {
                        Connect1});
            return ((ConnectResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void ConnectAsync(ConnectType Connect1) {
            this.ConnectAsync(Connect1, null);
        }
        
        /// <remarks/>
        public void ConnectAsync(ConnectType Connect1, object userState) {
            if ((this.ConnectOperationCompleted == null)) {
                this.ConnectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConnectOperationCompleted);
            }
            this.InvokeAsync("Connect", new object[] {
                        Connect1}, this.ConnectOperationCompleted, userState);
        }
        
        private void OnConnectOperationCompleted(object arg) {
            if ((this.ConnectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConnectCompleted(this, new ConnectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DisconnectResponse", Namespace="http://avid.com/inewssystem/types")]
        public DisconnectResponseType Disconnect([System.Xml.Serialization.XmlElementAttribute("Disconnect", Namespace="http://avid.com/inewssystem/types")] DisconnectType Disconnect1) {
            object[] results = this.Invoke("Disconnect", new object[] {
                        Disconnect1});
            return ((DisconnectResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void DisconnectAsync(DisconnectType Disconnect1) {
            this.DisconnectAsync(Disconnect1, null);
        }
        
        /// <remarks/>
        public void DisconnectAsync(DisconnectType Disconnect1, object userState) {
            if ((this.DisconnectOperationCompleted == null)) {
                this.DisconnectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisconnectOperationCompleted);
            }
            this.InvokeAsync("Disconnect", new object[] {
                        Disconnect1}, this.DisconnectOperationCompleted, userState);
        }
        
        private void OnDisconnectOperationCompleted(object arg) {
            if ((this.DisconnectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DisconnectCompleted(this, new DisconnectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsConnectedResponse", Namespace="http://avid.com/inewssystem/types")]
        public IsConnectedResponseType IsConnected([System.Xml.Serialization.XmlElementAttribute("IsConnected", Namespace="http://avid.com/inewssystem/types")] IsConnectedType IsConnected1) {
            object[] results = this.Invoke("IsConnected", new object[] {
                        IsConnected1});
            return ((IsConnectedResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void IsConnectedAsync(IsConnectedType IsConnected1) {
            this.IsConnectedAsync(IsConnected1, null);
        }
        
        /// <remarks/>
        public void IsConnectedAsync(IsConnectedType IsConnected1, object userState) {
            if ((this.IsConnectedOperationCompleted == null)) {
                this.IsConnectedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsConnectedOperationCompleted);
            }
            this.InvokeAsync("IsConnected", new object[] {
                        IsConnected1}, this.IsConnectedOperationCompleted, userState);
        }
        
        private void OnIsConnectedOperationCompleted(object arg) {
            if ((this.IsConnectedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsConnectedCompleted(this, new IsConnectedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetFolderChildrenResponse", Namespace="http://avid.com/inewssystem/types")]
        public GetFolderChildrenResponseType GetFolderChildren([System.Xml.Serialization.XmlElementAttribute("GetFolderChildren", Namespace="http://avid.com/inewssystem/types")] GetFolderChildrenType GetFolderChildren1) {
            object[] results = this.Invoke("GetFolderChildren", new object[] {
                        GetFolderChildren1});
            return ((GetFolderChildrenResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetFolderChildrenAsync(GetFolderChildrenType GetFolderChildren1) {
            this.GetFolderChildrenAsync(GetFolderChildren1, null);
        }
        
        /// <remarks/>
        public void GetFolderChildrenAsync(GetFolderChildrenType GetFolderChildren1, object userState) {
            if ((this.GetFolderChildrenOperationCompleted == null)) {
                this.GetFolderChildrenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFolderChildrenOperationCompleted);
            }
            this.InvokeAsync("GetFolderChildren", new object[] {
                        GetFolderChildren1}, this.GetFolderChildrenOperationCompleted, userState);
        }
        
        private void OnGetFolderChildrenOperationCompleted(object arg) {
            if ((this.GetFolderChildrenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFolderChildrenCompleted(this, new GetFolderChildrenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetMessageResponse", Namespace="http://avid.com/inewssystem/types")]
        public GetMessageResponseType GetMessage([System.Xml.Serialization.XmlElementAttribute("GetMessage", Namespace="http://avid.com/inewssystem/types")] GetMessageType GetMessage1) {
            object[] results = this.Invoke("GetMessage", new object[] {
                        GetMessage1});
            return ((GetMessageResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessageAsync(GetMessageType GetMessage1) {
            this.GetMessageAsync(GetMessage1, null);
        }
        
        /// <remarks/>
        public void GetMessageAsync(GetMessageType GetMessage1, object userState) {
            if ((this.GetMessageOperationCompleted == null)) {
                this.GetMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessageOperationCompleted);
            }
            this.InvokeAsync("GetMessage", new object[] {
                        GetMessage1}, this.GetMessageOperationCompleted, userState);
        }
        
        private void OnGetMessageOperationCompleted(object arg) {
            if ((this.GetMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessageCompleted(this, new GetMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("HasNewMessageResponse", Namespace="http://avid.com/inewssystem/types")]
        public HasNewMessageResponseType HasNewMessage([System.Xml.Serialization.XmlElementAttribute("HasNewMessage", Namespace="http://avid.com/inewssystem/types")] HasNewMessageType HasNewMessage1) {
            object[] results = this.Invoke("HasNewMessage", new object[] {
                        HasNewMessage1});
            return ((HasNewMessageResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void HasNewMessageAsync(HasNewMessageType HasNewMessage1) {
            this.HasNewMessageAsync(HasNewMessage1, null);
        }
        
        /// <remarks/>
        public void HasNewMessageAsync(HasNewMessageType HasNewMessage1, object userState) {
            if ((this.HasNewMessageOperationCompleted == null)) {
                this.HasNewMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHasNewMessageOperationCompleted);
            }
            this.InvokeAsync("HasNewMessage", new object[] {
                        HasNewMessage1}, this.HasNewMessageOperationCompleted, userState);
        }
        
        private void OnHasNewMessageOperationCompleted(object arg) {
            if ((this.HasNewMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HasNewMessageCompleted(this, new HasNewMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("SendMessageResponse", Namespace="http://avid.com/inewssystem/types")]
        public SendMessageResponseType SendMessage([System.Xml.Serialization.XmlElementAttribute("SendMessage", Namespace="http://avid.com/inewssystem/types")] SendMessageType SendMessage1) {
            object[] results = this.Invoke("SendMessage", new object[] {
                        SendMessage1});
            return ((SendMessageResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void SendMessageAsync(SendMessageType SendMessage1) {
            this.SendMessageAsync(SendMessage1, null);
        }
        
        /// <remarks/>
        public void SendMessageAsync(SendMessageType SendMessage1, object userState) {
            if ((this.SendMessageOperationCompleted == null)) {
                this.SendMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMessageOperationCompleted);
            }
            this.InvokeAsync("SendMessage", new object[] {
                        SendMessage1}, this.SendMessageOperationCompleted, userState);
        }
        
        private void OnSendMessageOperationCompleted(object arg) {
            if ((this.SendMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMessageCompleted(this, new SendMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetQueuesFormResponse", Namespace="http://avid.com/inewssystem/types")]
        public GetQueuesFormResponseType GetQueuesForm([System.Xml.Serialization.XmlElementAttribute("GetQueuesForm", Namespace="http://avid.com/inewssystem/types")] GetQueuesFormType GetQueuesForm1) {
            object[] results = this.Invoke("GetQueuesForm", new object[] {
                        GetQueuesForm1});
            return ((GetQueuesFormResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetQueuesFormAsync(GetQueuesFormType GetQueuesForm1) {
            this.GetQueuesFormAsync(GetQueuesForm1, null);
        }
        
        /// <remarks/>
        public void GetQueuesFormAsync(GetQueuesFormType GetQueuesForm1, object userState) {
            if ((this.GetQueuesFormOperationCompleted == null)) {
                this.GetQueuesFormOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetQueuesFormOperationCompleted);
            }
            this.InvokeAsync("GetQueuesForm", new object[] {
                        GetQueuesForm1}, this.GetQueuesFormOperationCompleted, userState);
        }
        
        private void OnGetQueuesFormOperationCompleted(object arg) {
            if ((this.GetQueuesFormCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetQueuesFormCompleted(this, new GetQueuesFormCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("WatchQueueForChangesResponse", Namespace="http://avid.com/inewssystem/types")]
        public WatchQueueForChangesResponseType WatchQueueForChanges([System.Xml.Serialization.XmlElementAttribute("WatchQueueForChanges", Namespace="http://avid.com/inewssystem/types")] WatchQueueForChangesType WatchQueueForChanges1) {
            object[] results = this.Invoke("WatchQueueForChanges", new object[] {
                        WatchQueueForChanges1});
            return ((WatchQueueForChangesResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void WatchQueueForChangesAsync(WatchQueueForChangesType WatchQueueForChanges1) {
            this.WatchQueueForChangesAsync(WatchQueueForChanges1, null);
        }
        
        /// <remarks/>
        public void WatchQueueForChangesAsync(WatchQueueForChangesType WatchQueueForChanges1, object userState) {
            if ((this.WatchQueueForChangesOperationCompleted == null)) {
                this.WatchQueueForChangesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWatchQueueForChangesOperationCompleted);
            }
            this.InvokeAsync("WatchQueueForChanges", new object[] {
                        WatchQueueForChanges1}, this.WatchQueueForChangesOperationCompleted, userState);
        }
        
        private void OnWatchQueueForChangesOperationCompleted(object arg) {
            if ((this.WatchQueueForChangesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WatchQueueForChangesCompleted(this, new WatchQueueForChangesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetChangedQueuesResponse", Namespace="http://avid.com/inewssystem/types")]
        public GetChangedQueuesResponseType GetChangedQueues([System.Xml.Serialization.XmlElementAttribute("GetChangedQueues", Namespace="http://avid.com/inewssystem/types")] GetChangedQueuesType GetChangedQueues1) {
            object[] results = this.Invoke("GetChangedQueues", new object[] {
                        GetChangedQueues1});
            return ((GetChangedQueuesResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void GetChangedQueuesAsync(GetChangedQueuesType GetChangedQueues1) {
            this.GetChangedQueuesAsync(GetChangedQueues1, null);
        }
        
        /// <remarks/>
        public void GetChangedQueuesAsync(GetChangedQueuesType GetChangedQueues1, object userState) {
            if ((this.GetChangedQueuesOperationCompleted == null)) {
                this.GetChangedQueuesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChangedQueuesOperationCompleted);
            }
            this.InvokeAsync("GetChangedQueues", new object[] {
                        GetChangedQueues1}, this.GetChangedQueuesOperationCompleted, userState);
        }
        
        private void OnGetChangedQueuesOperationCompleted(object arg) {
            if ((this.GetChangedQueuesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChangedQueuesCompleted(this, new GetChangedQueuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RemoveWatchForQueueChangesResponse", Namespace="http://avid.com/inewssystem/types")]
        public RemoveWatchForQueueChangesResponseType RemoveWatchForQueueChanges([System.Xml.Serialization.XmlElementAttribute("RemoveWatchForQueueChanges", Namespace="http://avid.com/inewssystem/types")] RemoveWatchForQueueChangesType RemoveWatchForQueueChanges1) {
            object[] results = this.Invoke("RemoveWatchForQueueChanges", new object[] {
                        RemoveWatchForQueueChanges1});
            return ((RemoveWatchForQueueChangesResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveWatchForQueueChangesAsync(RemoveWatchForQueueChangesType RemoveWatchForQueueChanges1) {
            this.RemoveWatchForQueueChangesAsync(RemoveWatchForQueueChanges1, null);
        }
        
        /// <remarks/>
        public void RemoveWatchForQueueChangesAsync(RemoveWatchForQueueChangesType RemoveWatchForQueueChanges1, object userState) {
            if ((this.RemoveWatchForQueueChangesOperationCompleted == null)) {
                this.RemoveWatchForQueueChangesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveWatchForQueueChangesOperationCompleted);
            }
            this.InvokeAsync("RemoveWatchForQueueChanges", new object[] {
                        RemoveWatchForQueueChanges1}, this.RemoveWatchForQueueChangesOperationCompleted, userState);
        }
        
        private void OnRemoveWatchForQueueChangesOperationCompleted(object arg) {
            if ((this.RemoveWatchForQueueChangesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveWatchForQueueChangesCompleted(this, new RemoveWatchForQueueChangesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("PerformSimpleSearchResponse", Namespace="http://avid.com/inewssystem/types")]
        public PerformSimpleSearchResponseType PerformSimpleSearch([System.Xml.Serialization.XmlElementAttribute("PerformSimpleSearch", Namespace="http://avid.com/inewssystem/types")] PerformSimpleSearchType PerformSimpleSearch1) {
            object[] results = this.Invoke("PerformSimpleSearch", new object[] {
                        PerformSimpleSearch1});
            return ((PerformSimpleSearchResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void PerformSimpleSearchAsync(PerformSimpleSearchType PerformSimpleSearch1) {
            this.PerformSimpleSearchAsync(PerformSimpleSearch1, null);
        }
        
        /// <remarks/>
        public void PerformSimpleSearchAsync(PerformSimpleSearchType PerformSimpleSearch1, object userState) {
            if ((this.PerformSimpleSearchOperationCompleted == null)) {
                this.PerformSimpleSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPerformSimpleSearchOperationCompleted);
            }
            this.InvokeAsync("PerformSimpleSearch", new object[] {
                        PerformSimpleSearch1}, this.PerformSimpleSearchOperationCompleted, userState);
        }
        
        private void OnPerformSimpleSearchOperationCompleted(object arg) {
            if ((this.PerformSimpleSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PerformSimpleSearchCompleted(this, new PerformSimpleSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RetrieveSearchResultsResponse", Namespace="http://avid.com/inewssystem/types")]
        public RetrieveSearchResultsResponseType RetrieveSearchResults([System.Xml.Serialization.XmlElementAttribute("RetrieveSearchResults", Namespace="http://avid.com/inewssystem/types")] RetrieveSearchResultsType RetrieveSearchResults1) {
            object[] results = this.Invoke("RetrieveSearchResults", new object[] {
                        RetrieveSearchResults1});
            return ((RetrieveSearchResultsResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveSearchResultsAsync(RetrieveSearchResultsType RetrieveSearchResults1) {
            this.RetrieveSearchResultsAsync(RetrieveSearchResults1, null);
        }
        
        /// <remarks/>
        public void RetrieveSearchResultsAsync(RetrieveSearchResultsType RetrieveSearchResults1, object userState) {
            if ((this.RetrieveSearchResultsOperationCompleted == null)) {
                this.RetrieveSearchResultsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveSearchResultsOperationCompleted);
            }
            this.InvokeAsync("RetrieveSearchResults", new object[] {
                        RetrieveSearchResults1}, this.RetrieveSearchResultsOperationCompleted, userState);
        }
        
        private void OnRetrieveSearchResultsOperationCompleted(object arg) {
            if ((this.RetrieveSearchResultsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveSearchResultsCompleted(this, new RetrieveSearchResultsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RegisterNotificationServiceResponse", Namespace="http://avid.com/inewssystem/types")]
        public RegisterNotificationServiceResponseType RegisterNotificationService([System.Xml.Serialization.XmlElementAttribute("RegisterNotificationService", Namespace="http://avid.com/inewssystem/types")] RegisterNotificationServiceType RegisterNotificationService1) {
            object[] results = this.Invoke("RegisterNotificationService", new object[] {
                        RegisterNotificationService1});
            return ((RegisterNotificationServiceResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterNotificationServiceAsync(RegisterNotificationServiceType RegisterNotificationService1) {
            this.RegisterNotificationServiceAsync(RegisterNotificationService1, null);
        }
        
        /// <remarks/>
        public void RegisterNotificationServiceAsync(RegisterNotificationServiceType RegisterNotificationService1, object userState) {
            if ((this.RegisterNotificationServiceOperationCompleted == null)) {
                this.RegisterNotificationServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterNotificationServiceOperationCompleted);
            }
            this.InvokeAsync("RegisterNotificationService", new object[] {
                        RegisterNotificationService1}, this.RegisterNotificationServiceOperationCompleted, userState);
        }
        
        private void OnRegisterNotificationServiceOperationCompleted(object arg) {
            if ((this.RegisterNotificationServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterNotificationServiceCompleted(this, new RegisterNotificationServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("CancelSearchResponse", Namespace="http://avid.com/inewssystem/types")]
        public CancelSearchResponseType CancelSearch([System.Xml.Serialization.XmlElementAttribute("CancelSearch", Namespace="http://avid.com/inewssystem/types")] CancelSearchType CancelSearch1) {
            object[] results = this.Invoke("CancelSearch", new object[] {
                        CancelSearch1});
            return ((CancelSearchResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void CancelSearchAsync(CancelSearchType CancelSearch1) {
            this.CancelSearchAsync(CancelSearch1, null);
        }
        
        /// <remarks/>
        public void CancelSearchAsync(CancelSearchType CancelSearch1, object userState) {
            if ((this.CancelSearchOperationCompleted == null)) {
                this.CancelSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelSearchOperationCompleted);
            }
            this.InvokeAsync("CancelSearch", new object[] {
                        CancelSearch1}, this.CancelSearchOperationCompleted, userState);
        }
        
        private void OnCancelSearchOperationCompleted(object arg) {
            if ((this.CancelSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelSearchCompleted(this, new CancelSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class ConnectType {
        
        private string usernameField;
        
        private string passwordField;
        
        private string servernameField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Servername {
            get {
                return this.servernameField;
            }
            set {
                this.servernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class CancelSearchResponseType {
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class ExtensionType {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class CancelSearchType {
        
        private long searchIDField;
        
        /// <remarks/>
        public long SearchID {
            get {
                return this.searchIDField;
            }
            set {
                this.searchIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class RegisterNotificationServiceResponseType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class RegisterNotificationServiceType {
        
        private string serviceURLField;
        
        /// <remarks/>
        public string ServiceURL {
            get {
                return this.serviceURLField;
            }
            set {
                this.serviceURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewsstory/types")]
    public partial class StoryType {
        
        private string fullPathField;
        
        private string queueLocatorField;
        
        private string storyAsNSMLField;
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string FullPath {
            get {
                return this.fullPathField;
            }
            set {
                this.fullPathField = value;
            }
        }
        
        /// <remarks/>
        public string QueueLocator {
            get {
                return this.queueLocatorField;
            }
            set {
                this.queueLocatorField = value;
            }
        }
        
        /// <remarks/>
        public string StoryAsNSML {
            get {
                return this.storyAsNSMLField;
            }
            set {
                this.storyAsNSMLField = value;
            }
        }
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class RetrieveSearchResultsResponseType {
        
        private SearchStatusType searchStatusField;
        
        private StoryType[] storiesField;
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public SearchStatusType SearchStatus {
            get {
                return this.searchStatusField;
            }
            set {
                this.searchStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stories")]
        public StoryType[] Stories {
            get {
                return this.storiesField;
            }
            set {
                this.storiesField = value;
            }
        }
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public enum SearchStatusType {
        
        /// <remarks/>
        Incomplete,
        
        /// <remarks/>
        Done,
        
        /// <remarks/>
        Aborted,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class RetrieveSearchResultsType {
        
        private long searchIDField;
        
        private bool returnFullStoryField;
        
        /// <remarks/>
        public long SearchID {
            get {
                return this.searchIDField;
            }
            set {
                this.searchIDField = value;
            }
        }
        
        /// <remarks/>
        public bool ReturnFullStory {
            get {
                return this.returnFullStoryField;
            }
            set {
                this.returnFullStoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class PerformSimpleSearchResponseType {
        
        private long searchIDField;
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public long SearchID {
            get {
                return this.searchIDField;
            }
            set {
                this.searchIDField = value;
            }
        }
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class PerformSimpleSearchType {
        
        private SearchTypeType searchTypeField;
        
        private string searchPathField;
        
        private string[] searchWordsField;
        
        private SearchOperatorType searchOperatorField;
        
        private short numberOfParagraphsField;
        
        private short hitLimitField;
        
        /// <remarks/>
        public SearchTypeType SearchType {
            get {
                return this.searchTypeField;
            }
            set {
                this.searchTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SearchPath {
            get {
                return this.searchPathField;
            }
            set {
                this.searchPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SearchWords")]
        public string[] SearchWords {
            get {
                return this.searchWordsField;
            }
            set {
                this.searchWordsField = value;
            }
        }
        
        /// <remarks/>
        public SearchOperatorType SearchOperator {
            get {
                return this.searchOperatorField;
            }
            set {
                this.searchOperatorField = value;
            }
        }
        
        /// <remarks/>
        public short NumberOfParagraphs {
            get {
                return this.numberOfParagraphsField;
            }
            set {
                this.numberOfParagraphsField = value;
            }
        }
        
        /// <remarks/>
        public short HitLimit {
            get {
                return this.hitLimitField;
            }
            set {
                this.hitLimitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public enum SearchTypeType {
        
        /// <remarks/>
        Indexed,
        
        /// <remarks/>
        Fast,
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        Some,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public enum SearchOperatorType {
        
        /// <remarks/>
        And,
        
        /// <remarks/>
        Or,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class RemoveWatchForQueueChangesResponseType {
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class RemoveWatchForQueueChangesType {
        
        private string queueFullNameField;
        
        /// <remarks/>
        public string QueueFullName {
            get {
                return this.queueFullNameField;
            }
            set {
                this.queueFullNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class GetChangedQueuesResponseType {
        
        private string[] changedQueueNamesField;
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChangedQueueNames")]
        public string[] ChangedQueueNames {
            get {
                return this.changedQueueNamesField;
            }
            set {
                this.changedQueueNamesField = value;
            }
        }
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class GetChangedQueuesType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class WatchQueueForChangesResponseType {
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class WatchQueueForChangesType {
        
        private string queueFullNameField;
        
        /// <remarks/>
        public string QueueFullName {
            get {
                return this.queueFullNameField;
            }
            set {
                this.queueFullNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class GetQueuesFormResponseType {
        
        private string queueFullNameField;
        
        private string formField;
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public string QueueFullName {
            get {
                return this.queueFullNameField;
            }
            set {
                this.queueFullNameField = value;
            }
        }
        
        /// <remarks/>
        public string Form {
            get {
                return this.formField;
            }
            set {
                this.formField = value;
            }
        }
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class GetQueuesFormType {
        
        private string queueFullNameField;
        
        private FormTypeType formTypeField;
        
        /// <remarks/>
        public string QueueFullName {
            get {
                return this.queueFullNameField;
            }
            set {
                this.queueFullNameField = value;
            }
        }
        
        /// <remarks/>
        public FormTypeType FormType {
            get {
                return this.formTypeField;
            }
            set {
                this.formTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public enum FormTypeType {
        
        /// <remarks/>
        Queue,
        
        /// <remarks/>
        Story,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class SendMessageResponseType {
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class SendMessageType {
        
        private string recipientNameField;
        
        private string messageTextField;
        
        /// <remarks/>
        public string RecipientName {
            get {
                return this.recipientNameField;
            }
            set {
                this.recipientNameField = value;
            }
        }
        
        /// <remarks/>
        public string MessageText {
            get {
                return this.messageTextField;
            }
            set {
                this.messageTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class HasNewMessageResponseType {
        
        private bool hasMoreMessagesField;
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public bool HasMoreMessages {
            get {
                return this.hasMoreMessagesField;
            }
            set {
                this.hasMoreMessagesField = value;
            }
        }
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class HasNewMessageType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class GetMessageResponseType {
        
        private string messageTextField;
        
        private string recipientField;
        
        private string senderField;
        
        private System.DateTime sendDateField;
        
        private bool hasMoreMessagesField;
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public string MessageText {
            get {
                return this.messageTextField;
            }
            set {
                this.messageTextField = value;
            }
        }
        
        /// <remarks/>
        public string Recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
            }
        }
        
        /// <remarks/>
        public string Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SendDate {
            get {
                return this.sendDateField;
            }
            set {
                this.sendDateField = value;
            }
        }
        
        /// <remarks/>
        public bool HasMoreMessages {
            get {
                return this.hasMoreMessagesField;
            }
            set {
                this.hasMoreMessagesField = value;
            }
        }
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class GetMessageType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class DirectoryType {
        
        private DirectoryTypeType typeField;
        
        private string nameField;
        
        private string fullNameField;
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public DirectoryTypeType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public enum DirectoryTypeType {
        
        /// <remarks/>
        Queue,
        
        /// <remarks/>
        Folder,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class GetFolderChildrenResponseType {
        
        private string parentFolderFullNameField;
        
        private DirectoryType[] childrenField;
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public string ParentFolderFullName {
            get {
                return this.parentFolderFullNameField;
            }
            set {
                this.parentFolderFullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Children")]
        public DirectoryType[] Children {
            get {
                return this.childrenField;
            }
            set {
                this.childrenField = value;
            }
        }
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class GetFolderChildrenType {
        
        private string folderFullNameField;
        
        /// <remarks/>
        public string FolderFullName {
            get {
                return this.folderFullNameField;
            }
            set {
                this.folderFullNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class IsConnectedResponseType {
        
        private bool isConnectedField;
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public bool IsConnected {
            get {
                return this.isConnectedField;
            }
            set {
                this.isConnectedField = value;
            }
        }
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class IsConnectedType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class DisconnectResponseType {
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class DisconnectType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class ConnectResponseType {
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ConnectCompletedEventHandler(object sender, ConnectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConnectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConnectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConnectResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConnectResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DisconnectCompletedEventHandler(object sender, DisconnectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DisconnectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DisconnectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DisconnectResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DisconnectResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void IsConnectedCompletedEventHandler(object sender, IsConnectedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsConnectedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsConnectedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IsConnectedResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IsConnectedResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetFolderChildrenCompletedEventHandler(object sender, GetFolderChildrenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFolderChildrenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFolderChildrenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetFolderChildrenResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetFolderChildrenResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetMessageCompletedEventHandler(object sender, GetMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetMessageResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetMessageResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void HasNewMessageCompletedEventHandler(object sender, HasNewMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasNewMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HasNewMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HasNewMessageResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HasNewMessageResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SendMessageCompletedEventHandler(object sender, SendMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendMessageResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendMessageResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetQueuesFormCompletedEventHandler(object sender, GetQueuesFormCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetQueuesFormCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetQueuesFormCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetQueuesFormResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetQueuesFormResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void WatchQueueForChangesCompletedEventHandler(object sender, WatchQueueForChangesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WatchQueueForChangesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WatchQueueForChangesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WatchQueueForChangesResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WatchQueueForChangesResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetChangedQueuesCompletedEventHandler(object sender, GetChangedQueuesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChangedQueuesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChangedQueuesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetChangedQueuesResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetChangedQueuesResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RemoveWatchForQueueChangesCompletedEventHandler(object sender, RemoveWatchForQueueChangesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveWatchForQueueChangesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveWatchForQueueChangesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RemoveWatchForQueueChangesResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RemoveWatchForQueueChangesResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void PerformSimpleSearchCompletedEventHandler(object sender, PerformSimpleSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PerformSimpleSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PerformSimpleSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PerformSimpleSearchResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PerformSimpleSearchResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RetrieveSearchResultsCompletedEventHandler(object sender, RetrieveSearchResultsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveSearchResultsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveSearchResultsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetrieveSearchResultsResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetrieveSearchResultsResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RegisterNotificationServiceCompletedEventHandler(object sender, RegisterNotificationServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterNotificationServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterNotificationServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RegisterNotificationServiceResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RegisterNotificationServiceResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CancelSearchCompletedEventHandler(object sender, CancelSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CancelSearchResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CancelSearchResponseType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591