//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace iNews.LegacyWrapper.SoapClients.INEWSStory {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="INEWSStoryPortBinding", Namespace="http://avid.com/inewsstory")]
    public partial class INEWSStory : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LockStoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveStoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback UnlockStoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteStoryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public INEWSStory() {
            // this.Url = global::API_iNews.Properties.Settings.Default.API_iNews_INEWSStory_INEWSStory;
            this.Url = System.Configuration.ConfigurationManager.AppSettings["iNewsStoryUrl"] ?? "http://10.10.10.10:8080/inews/webservice/INEWSStory";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LockStoryCompletedEventHandler LockStoryCompleted;
        
        /// <remarks/>
        public event SaveStoryCompletedEventHandler SaveStoryCompleted;
        
        /// <remarks/>
        public event UnlockStoryCompletedEventHandler UnlockStoryCompleted;
        
        /// <remarks/>
        public event DeleteStoryCompletedEventHandler DeleteStoryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("LockStoryResponse", Namespace="http://avid.com/inewsstory/types")]
        public LockStoryResponseType LockStory([System.Xml.Serialization.XmlElementAttribute("LockStory", Namespace="http://avid.com/inewsstory/types")] LockStoryType LockStory1) {
            object[] results = this.Invoke("LockStory", new object[] {
                        LockStory1});
            return ((LockStoryResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void LockStoryAsync(LockStoryType LockStory1) {
            this.LockStoryAsync(LockStory1, null);
        }
        
        /// <remarks/>
        public void LockStoryAsync(LockStoryType LockStory1, object userState) {
            if ((this.LockStoryOperationCompleted == null)) {
                this.LockStoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLockStoryOperationCompleted);
            }
            this.InvokeAsync("LockStory", new object[] {
                        LockStory1}, this.LockStoryOperationCompleted, userState);
        }
        
        private void OnLockStoryOperationCompleted(object arg) {
            if ((this.LockStoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LockStoryCompleted(this, new LockStoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("SaveStoryResponse", Namespace="http://avid.com/inewsstory/types")]
        public SaveStoryResponseType SaveStory([System.Xml.Serialization.XmlElementAttribute("SaveStory", Namespace="http://avid.com/inewsstory/types")] SaveStoryType SaveStory1) {
            object[] results = this.Invoke("SaveStory", new object[] {
                        SaveStory1});
            return ((SaveStoryResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void SaveStoryAsync(SaveStoryType SaveStory1) {
            this.SaveStoryAsync(SaveStory1, null);
        }
        
        /// <remarks/>
        public void SaveStoryAsync(SaveStoryType SaveStory1, object userState) {
            if ((this.SaveStoryOperationCompleted == null)) {
                this.SaveStoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveStoryOperationCompleted);
            }
            this.InvokeAsync("SaveStory", new object[] {
                        SaveStory1}, this.SaveStoryOperationCompleted, userState);
        }
        
        private void OnSaveStoryOperationCompleted(object arg) {
            if ((this.SaveStoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveStoryCompleted(this, new SaveStoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UnlockStoryResponse", Namespace="http://avid.com/inewsstory/types")]
        public UnlockStoryResponseType UnlockStory([System.Xml.Serialization.XmlElementAttribute("UnlockStory", Namespace="http://avid.com/inewsstory/types")] UnlockStoryType UnlockStory1) {
            object[] results = this.Invoke("UnlockStory", new object[] {
                        UnlockStory1});
            return ((UnlockStoryResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void UnlockStoryAsync(UnlockStoryType UnlockStory1) {
            this.UnlockStoryAsync(UnlockStory1, null);
        }
        
        /// <remarks/>
        public void UnlockStoryAsync(UnlockStoryType UnlockStory1, object userState) {
            if ((this.UnlockStoryOperationCompleted == null)) {
                this.UnlockStoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnlockStoryOperationCompleted);
            }
            this.InvokeAsync("UnlockStory", new object[] {
                        UnlockStory1}, this.UnlockStoryOperationCompleted, userState);
        }
        
        private void OnUnlockStoryOperationCompleted(object arg) {
            if ((this.UnlockStoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UnlockStoryCompleted(this, new UnlockStoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeleteStoryResponse", Namespace="http://avid.com/inewsstory/types")]
        public DeleteStoryResponseType DeleteStory([System.Xml.Serialization.XmlElementAttribute("DeleteStory", Namespace="http://avid.com/inewsstory/types")] DeleteStoryType DeleteStory1) {
            object[] results = this.Invoke("DeleteStory", new object[] {
                        DeleteStory1});
            return ((DeleteStoryResponseType)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteStoryAsync(DeleteStoryType DeleteStory1) {
            this.DeleteStoryAsync(DeleteStory1, null);
        }
        
        /// <remarks/>
        public void DeleteStoryAsync(DeleteStoryType DeleteStory1, object userState) {
            if ((this.DeleteStoryOperationCompleted == null)) {
                this.DeleteStoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteStoryOperationCompleted);
            }
            this.InvokeAsync("DeleteStory", new object[] {
                        DeleteStory1}, this.DeleteStoryOperationCompleted, userState);
        }
        
        private void OnDeleteStoryOperationCompleted(object arg) {
            if ((this.DeleteStoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteStoryCompleted(this, new DeleteStoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewsstory/types")]
    public partial class LockStoryType {
        
        private string queueFullNameField;
        
        private string queueLocatorField;
        
        private SectionLockEnum sectionField;
        
        private bool sectionFieldSpecified;
        
        /// <remarks/>
        public string QueueFullName {
            get {
                return this.queueFullNameField;
            }
            set {
                this.queueFullNameField = value;
            }
        }
        
        /// <remarks/>
        public string QueueLocator {
            get {
                return this.queueLocatorField;
            }
            set {
                this.queueLocatorField = value;
            }
        }
        
        /// <remarks/>
        public SectionLockEnum Section {
            get {
                return this.sectionField;
            }
            set {
                this.sectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SectionSpecified {
            get {
                return this.sectionFieldSpecified;
            }
            set {
                this.sectionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewsstory/types")]
    public enum SectionLockEnum {
        
        /// <remarks/>
        BODY,
        
        /// <remarks/>
        FORM,
        
        /// <remarks/>
        ALL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewsstory/types")]
    public partial class DeleteStoryResponseType {
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewssystem/types")]
    public partial class ExtensionType {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewsstory/types")]
    public partial class DeleteStoryType {
        
        private string queueFullNameField;
        
        private string queueLocatorField;
        
        /// <remarks/>
        public string QueueFullName {
            get {
                return this.queueFullNameField;
            }
            set {
                this.queueFullNameField = value;
            }
        }
        
        /// <remarks/>
        public string QueueLocator {
            get {
                return this.queueLocatorField;
            }
            set {
                this.queueLocatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewsstory/types")]
    public partial class UnlockStoryResponseType {
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewsstory/types")]
    public partial class UnlockStoryType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewsstory/types")]
    public partial class StoryType {
        
        private string fullPathField;
        
        private string queueLocatorField;
        
        private string storyAsNSMLField;
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string FullPath {
            get {
                return this.fullPathField;
            }
            set {
                this.fullPathField = value;
            }
        }
        
        /// <remarks/>
        public string QueueLocator {
            get {
                return this.queueLocatorField;
            }
            set {
                this.queueLocatorField = value;
            }
        }
        
        /// <remarks/>
        public string StoryAsNSML {
            get {
                return this.storyAsNSMLField;
            }
            set {
                this.storyAsNSMLField = value;
            }
        }
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewsstory/types")]
    public partial class SaveStoryResponseType {
        
        private StoryType storySavedField;
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public StoryType StorySaved {
            get {
                return this.storySavedField;
            }
            set {
                this.storySavedField = value;
            }
        }
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewsstory/types")]
    public partial class SaveStoryType {
        
        private string storyNSMLField;
        
        /// <remarks/>
        public string StoryNSML {
            get {
                return this.storyNSMLField;
            }
            set {
                this.storyNSMLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://avid.com/inewsstory/types")]
    public partial class LockStoryResponseType {
        
        private ExtensionType extensionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LockStoryCompletedEventHandler(object sender, LockStoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LockStoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LockStoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LockStoryResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LockStoryResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SaveStoryCompletedEventHandler(object sender, SaveStoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveStoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveStoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SaveStoryResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SaveStoryResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void UnlockStoryCompletedEventHandler(object sender, UnlockStoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UnlockStoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UnlockStoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UnlockStoryResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UnlockStoryResponseType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DeleteStoryCompletedEventHandler(object sender, DeleteStoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteStoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteStoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeleteStoryResponseType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeleteStoryResponseType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591